# Generated by Django 6.0.5 on 2026-05-13 14:45

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("level", models.CharField(max_length=10)),
                ("logger_name", models.CharField(db_index=True, max_length=200)),
                ("message", models.TextField()),
                ("module", models.CharField(max_length=200)),
                ("pathname", models.CharField(max_length=500)),
                ("line_number", models.IntegerField()),
            ],
            options={
                "verbose_name": "Log",
                "verbose_name_plural": "Logs",
                "db_table": "log_panel_log",
                "indexes": [
                    models.Index(
                        fields=["timestamp", "logger_name", "level"],
                        name="timestamp_logger_level",
                    ),
                    models.Index(
                        fields=["logger_name", "-timestamp"],
                        name="logger_name_timestamp",
                    ),
                ],
            },
        ),
    ]
