# Generated by Django 6.0.3 on 2026-04-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Panel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("level", models.CharField(max_length=10)),
                ("logger_name", models.CharField(db_index=True, max_length=200)),
                ("message", models.TextField()),
                ("module", models.CharField(max_length=200)),
                ("pathname", models.CharField(max_length=500)),
                ("line_number", models.IntegerField()),
            ],
            options={
                "verbose_name": "Panel",
                "verbose_name_plural": "Panels",
            },
        ),
    ]
