# Generated by Django 6.0.5 on 2026-05-13 20:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_panel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="message_chunked",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="log",
            name="message_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="LogMessageChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_chunks",
                        to="log_panel.log",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log message chunk",
                "verbose_name_plural": "Log message chunks",
                "db_table": "log_panel_log_message_chunk",
                "indexes": [
                    models.Index(
                        fields=["log", "index"], name="log_message_chunk_order"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("log", "index"), name="unique_log_message_chunk"
                    )
                ],
            },
        ),
    ]
