# Generated by Django 6.0.4 on 2026-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_panel", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Panel",
            new_name="Log",
        ),
        migrations.AlterModelOptions(
            name="log",
            options={"verbose_name": "Log", "verbose_name_plural": "Logs"},
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["timestamp", "logger_name", "level"],
                name="timestamp_logger_level",
            ),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(
                fields=["logger_name", "-timestamp"], name="logger_name_timestamp"
            ),
        ),
        migrations.AlterModelTable(
            name="log",
            table="log_panel_log",
        ),
    ]
