# Generated by Django 6.0.5 on 2026-05-13 13:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_panel', '0002_rename_panel_log_alter_log_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
