# Generated by Django 6.0.5 on 2026-05-19 11:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_panel", "0002_log_message_chunked_log_message_size_logmessagechunk"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "log_panel_logger",
            },
        ),
        migrations.CreateModel(
            name="LogCard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total", models.PositiveBigIntegerField(default=0)),
                ("total_errors", models.PositiveBigIntegerField(default=0)),
                ("total_warnings", models.PositiveBigIntegerField(default=0)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "logger",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card",
                        to="log_panel.logger",
                    ),
                ),
            ],
            options={
                "db_table": "log_panel_log_card",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="LogTimelineBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bucket", models.DateTimeField()),
                ("unit", models.CharField(max_length=4)),
                ("log_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                (
                    "logger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline_buckets",
                        to="log_panel.logger",
                    ),
                ),
            ],
            options={
                "db_table": "log_panel_log_timeline_bucket",
                "indexes": [
                    models.Index(
                        fields=["logger", "unit", "bucket"],
                        name="timeline_logger_unit_bucket",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("logger", "bucket", "unit"),
                        name="unique_timeline_bucket",
                    )
                ],
            },
        ),
    ]
