# Generated by Django 6.0.5 on 2026-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_panel", "0003_logger_logcard_logtimelinebucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logtimelinebucket",
            name="unit",
            field=models.CharField(
                choices=[("hour", "hour"), ("day", "day")], max_length=4
            ),
        ),
    ]
